// export const localizedStrings = {

    

//     duration: {
//         es: "{days} días / {nights} noches",
//         en: "{days} days / {nights} nights",
//         ar: "{days} أيام / {nights} ليالٍ"
//     },
//     askForCategory: {
//         es: "¡Excelente elección! Para darte el precio exacto, ¿prefieres la categoría Gold o la categoría Diamond para tu viaje?",
//         en: "Excellent choice! To give you the exact price, do you prefer the Gold or Diamond category for your trip?",
//         ar: "اختيار ممتاز! لإعطائك السعر الدقيق، هل تفضل فئة الذهب أم فئة الألماس لرحلتك؟"
//     },
//     pricePerPerson: {
//         es: "Precio por persona en",
//         en: "Price per person in",
//         ar: "السعر للشخص الواحد في"
//     },
//     double: { es: "habitación doble", en: "double room", ar: "غرفة مزدوجة" },
//     triple: { es: "habitación triple", en: "triple room", ar: "غرفة ثلاثية" },
//     single: { es: "habitación single", en: "single room", ar: "غرفة فردية" },
//     summer: { es: "Temporada de Verano (Mayo-Sept)", en: "Summer Season (May-Sept)", ar: "موسم الصيف (مايو-سبتمبر)" },
//     winter: { es: "Temporada de Invierno (Oct-Abr)", en: "Winter Season (Oct-Apr)", ar: "موسم الشتاء (أكتوبر-أبريل)" },
//     seasonalDisclaimer: {
//         es: "Estos precios son orientativos y pueden variar ligeramente según la fecha exacta del viaje.",
//         en: "These prices are estimates and may vary slightly depending on the exact travel date.",
//         ar: "هذه الأسعار تقديرية وقد تختلف قليلاً حسب تاريخ السفر الدقيق."
//     },
//     diversifiedCtas: {
//       es: [
//         "¿Te gustaría que te envíe el itinerario detallado de este programa?",
//         "¿Quieres que te muestre los hoteles de lujo que incluye este viaje?",
//         "Si este programa te inspira, puedo contarte más sobre las experiencias únicas que incluye.",
//         "¿Hay algo más que te gustaría saber sobre este viaje ancestral?",
//         "Puedo explicarte qué servicios exclusivos hacen de este programa una experiencia inolvidable. ¿Te interesa?"
//       ],
//       en: [
//         "Would you like me to send you the detailed itinerary for this program?",
//         "Do you want me to show you the luxury hotels included in this trip?",
//         "If this program inspires you, I can tell you more about the unique experiences it includes.",
//         "Is there anything else you would like to know about this ancestral journey?",
//         "I can explain the exclusive services that make this program an unforgettable experience. Are you interested?"
//       ],
//       ar: [
//         "هل تود أن أرسل لك خط سير الرحلة المفصل لهذا البرنامج؟",
//         "هل تريد أن أريك الفنادق الفاخرة التي تشملها هذه الرحلة؟",
//         "إذا كان هذا البرنامج يلهمك، يمكنني أن أخبرك المزيد عن التجارب الفريدة التي يتضمنها.",
//         "هل هناك أي شيء آخر تود معرفته عن هذه الرحلة القديمة؟",
//         "يمكنني أن أشرح لك الخدمات الحصرية التي تجعل هذا البرنامج تجربة لا تُنسى. هل أنت مهتم؟"
//       ]
//     },
//     ui: {
//         es: {
//             welcomeMessages: [
//                 "Bienvenido a Egiptura. Imagina el sol dorado sobre las Pirámides mientras un guía experto te revela sus secretos. Soy tu asesor de viajes de lujo, ¿qué aventura soñaste para Egipto?",
//                 "Un cordial saludo desde la tierra de los faraones. En Egiptura, diseñamos más que viajes; creamos legados. ¿Estás listo para empezar a diseñar el tuyo?",
//                 "Bienvenido. Piensa en el murmullo del Nilo desde la cubierta de un crucero de lujo. Esa es la paz que ofrecemos. Soy tu consejero personal en Egiptura, ¿cómo podemos empezar a trazar tu mapa?",
//             ],
//             tagline: "Tu guía a los secretos de Egipto",
//             sendButton: "Enviar",
//             suggestions: [
//                 "Quiero un viaje de 8 días con crucero",
//                 "¿Qué programas tenéis disponibles?",
//                 "Háblame sobre la categoría Diamond",
//                 "Necesito un viaje a medida",
//                 "¿Es seguro viajar a Egipto?",
//                 "Muéstrame un viaje corto a El Cairo",
//             ],
//             loadingMessages: [
//                 "Consultando los antiguos papiros...",
//                 "Trazando tu ruta en el mapa de los faraones...",
//                 "Añadiendo un toque de magia a tu itinerario...",
//                 "Diseñando una experiencia única para ti...",
//                 "Puliendo los detalles de tu próxima gran aventura...",
//             ],
//             chatPlaceholder: "Escribe tu consulta sobre Egipto...",
//             cardViewDetails: "Ver detalles",
//             cardRequestQuote: "Solicitar cotización",
//             cardSaveChanges: "Guardar Viaje",
//             cardShare: "Compartir Viaje",
//             cardLoadSaved: "Cargar Viaje Guardado",
//             cardNights: "noches",
//             cardDays: "días",
//             cardLabelDuration: "Días / Noches",
//             cardLabelCruiseNights: "Noches Crucero",
//             cardNightCruise: "noche en crucero",
//             cardNightsCruise: "noches en crucero",
//             cardStart: "inicio",
//             cardGuide: "guía",
//             modalOverview: "Resumen",
//             modalItinerary: "Itinerario",
//             modalAccommodation: "Alojamiento",
//             modalPricing: "Precios y Opciones",
//             modalIncluded: "Servicios Incluidos",
//             modalExcluded: "Servicios Excluidos",
//             modalImportantNotes: "Notas Importantes",
//             modalSelectCategory: "1. Selecciona una categoría",
//             modalCategoryGold: "Categoría Gold",
//             modalCategoryGoldDesc: "Hoteles 5★ y servicio personalizado.",
//             modalCategoryDiamond: "Categoría Diamond",
//             modalCategoryDiamondDesc: "Lujo 5★ Deluxe y experiencias VIP.",
//             modalPricesBySeason: "2. Precios por temporada",
//             modalSummerSeason: "Temporada de Verano (Mayo-Sept)",
//             modalWinterSeason: "Temporada de Invierno (Oct-Abr)",
//             modalPriceDouble: "Habitación Doble",
//             modalPriceTriple: "Habitación Triple",
//             modalPriceSingle: "Habitación Individual",
//             modalPerPerson: "por persona",
//             modalItineraryOptions: "Este programa tiene múltiples rutas. Selecciona una opción:",
//             modalQuoteButton: "Solicitar Cotización",
//             modalContactButton: "Contactar Agente",
//             modalExchangeRate: "Tipo de cambio oficial hoy:",
//             modalExchangeRateDisclaimer: "Los precios son en USD.",
//             modalDay: "Día",
//             modalCategory: "Categoría",
//             sampleAccommodations: "Alojamientos de Muestra",
//             modalInfoDaysNights: "días / noches",
//             modalInfoStartIn: "Inicia en",
//             modalInfoCruiseNights: "noches en crucero",
//             modalInfoCategories: "Categorías",
//             customQuoteTitle: "Tu Viaje Personalizado de {duration} Días",
//             customQuoteCategory: "Categoría {category}",
//             customQuoteOverviewText: "Un resumen de su viaje personalizado de {duration} días para {travelers} viajeros, explorando los tesoros de Egipto.",
//             customQuoteTabOverview: "Resumen",
//             customQuoteTabItinerary: "Día a Día",
//             customQuoteTabPricing: "Precios",
//             customQuoteCreated: "¡He diseñado un viaje especialmente para ti! Aquí tienes todos los detalles.",
//             totalGroupPriceLabel: "Precio Total del Grupo",
//             forTravelersLabel: "Para {travelers} viajeros",
//             pricePerPersonLabel: "Precio Por Persona",
//             averageLabel: "(promedio)",
            
//             // Fallback Generation Strings
//             fallbackDayTitles: {
//                 arrival: { es: "Llegada a El Cairo, la Tierra de los Faraones", en: "Arrival in Cairo, Land of the Pharaohs", ar: "الوصول إلى القاهرة، أرض الفراعنة" },
//                 cairoTour: { es: "Explorando los Tesoros de El Cairo", en: "Exploring the Treasures of Cairo", ar: "استكشاف كنوز القاهرة" },
//                 flyToCruise: { es: "Vuelo a Lúxor/Asuán e Inicio del Crucero", en: "Flight to Luxor/Aswan & Cruise Embarkation", ar: "رحلة طيران إلى الأقصر/أسوان وبدء الرحلة النيلية" },
//                 nileSailing: { es: "Navegando las Aguas Eternas del Nilo", en: "Sailing the Eternal Waters of the Nile", ar: "الإبحار في مياه النيل الخالدة" },
//                 returnToCairo: { es: "Regreso a la Vibrante Capital", en: "Return to the Vibrant Capital", ar: "العودة إلى العاصمة النابضة بالحياة" },
//                 departure: { es: "Salida de El Cairo con Recuerdos Inolvidables", en: "Departure from Cairo with Unforgettable Memories", ar: "المغادرة من القاهرة بذكريات لا تُنسى" },
//             },
//             fallbackDayActivities: {
//                 arrival: {
//                     en: ["Upon arrival at Cairo International Airport, our representative will give you a warm welcome and assist with visa procedures. Afterwards, a private transfer will take you to your hotel to check in and rest. (Accommodation with breakfast)."],
//                     es: ["A tu llegada al Aeropuerto Internacional de El Cairo, nuestro representante te dará una cálida bienvenida y te ayudará con los trámites de visado. Luego, un traslado privado te llevará a tu hotel para que te instales y descanses. (Alojamiento con desayuno)."],
//                     ar: ["عند وصولك إلى مطار القاهرة الدولي، سيستقبلك ممثلنا بحفاوة ويساعدك في إجراءات التأشيرة. بعد ذلك، ستنقلك سيارة خاصة إلى فندقك لتسجيل الدخول والراحة. (إقامة مع وجبة الإفطار)."]
//                 },
//                 cairoFreeDay: {
//                     en: [
//                     "Breakfast at your hotel. Visit the Egyptian Museum and the Great Pyramids of Giza.",
//                     "Breakfast at your hotel. Explore Islamic Cairo and Khan El Khalili Bazaar.",
//                     "Breakfast at your hotel. Enjoy a full-day optional tour to Memphis and Saqqara."
//                     ],
//                     es: [
//                     "Desayuno en tu hotel. Visita el Museo Egipcio y las Grandes Pirámides de Guiza.",
//                     "Desayuno en tu hotel. Explora El Cairo Islámico y el bazar Khan El Khalili.",
//                     "Desayuno en tu hotel. Excursión opcional de día completo a Menfis y Saqqara."
//                     ],
//                     ar: [
//                     "إفطار في فندقك. زيارة المتحف المصري والأهرامات الكبرى بالجيزة.",
//                     "إفطار في فندقك. استكشاف القاهرة الإسلامية وخان الخليلي.",
//                     "إفطار في فندقك. جولة اختيارية ليوم كامل إلى ممفيس وسقارة."
//                     ]
//                 },
//                 flyToCruise: {
//                     en: ["Breakfast at your Cairo hotel. Flight to Luxor or Aswan and embark your luxury Nile cruise. Enjoy lunch and dinner on board (Full board)."],
//                     es: ["Desayuno en tu hotel de El Cairo. Vuelo a Lúxor o Asuán y embarque en tu crucero de lujo. Disfruta del almuerzo y la cena a bordo (Pensión completa)."],
//                     ar: ["إفطار في فندقك بالقاهرة. رحلة طيران إلى الأقصر أو أسوان وبدء الرحلة النيلية. استمتع بالغداء والعشاء على متن السفينة (إقامة كاملة)."]
//                 },
//                 nileSailing: {
//                     en: [
//                     "Sail to Edfu and visit the Temple of Horus.",
//                     "Continue to Kom Ombo to explore the twin temples of Sobek and Haroeris.",
//                     "Enjoy the beauty of the Nile while relaxing on board and watching rural life pass by."
//                     ],
//                     es: [
//                     "Navega a Edfu y visita el Templo de Horus.",
//                     "Continúa hacia Kom Ombo para explorar los templos gemelos de Sobek y Haroeris.",
//                     "Disfruta de la belleza del Nilo mientras te relajas a bordo observando la vida rural."
//                     ],
//                     ar: [
//                     "الإبحار إلى إدفو وزيارة معبد حورس.",
//                     "مواصلة الرحلة إلى كوم أمبو لاستكشاف المعبدين التوأمين للإله سوبك وحوروريس.",
//                     "استمتع بجمال النيل أثناء الاسترخاء على متن السفينة ومشاهدة الحياة الريفية تمر بجانبك."
//                     ]
//                 },
//                 returnToCairo: {
//                     en: ["After breakfast, disembark and fly back to Cairo. Transfer to your hotel for your final night."],
//                     es: ["Después del desayuno, desembarca y vuela de regreso a El Cairo. Traslado a tu hotel para tu última noche."],
//                     ar: ["بعد الإفطار، النزول من السفينة والعودة إلى القاهرة. الانتقال إلى الفندق لليلة الأخيرة."]
//                 },
//                 departure: {
//                     en: ["Breakfast at your hotel. Transfer to Cairo International Airport for your return flight."],
//                     es: ["Desayuno en tu hotel. Traslado al Aeropuerto Internacional de El Cairo para tu vuelo de regreso."],
//                     ar: ["إفطار في فندقك. الانتقال إلى مطار القاهرة الدولي لرحلة العودة."]
//                 }
//                 },

//             optionalToursByCity: {
//                 cairo: { es: "el Museo de la Civilización Egipcia, el histórico Cairo Copto o un paseo en faluca por el Nilo", en: "the Museum of Egyptian Civilization, historic Coptic Cairo, or a felucca ride on the Nile", ar: "متحف الحضارة المصرية، القاهرة القبطية التاريخية، أو جولة بالفلوكة في النيل" },
//                 luxor: { es: "un vuelo en globo al amanecer sobre el Valle de los Reyes o el espectáculo de Luz y Sonido en el Templo de Karnak", en: "a sunrise hot air balloon ride over the Valley of the Kings or the Sound and Light show at Karnak Temple", ar: "رحلة بالمنطاد عند شروق الشمس فوق وادي الملوك أو عرض الصوت والضوء في معبد الكرنك" },
//                 aswan: { es: "el poblado Nubio para conocer su vibrante cultura, o los Jardines Botánicos en la Isla de Kitchener", en: "the Nubian village to experience its vibrant culture, or the Botanical Gardens on Kitchener's Island", ar: "القرية النوبية لتجربة ثقافتهم النابضة بالحياة، أو الحدائق النباتية في جزيرة كتشنر" },
//             },
//             serviceStrings: {
//                 accommodation: { es: "{nights} noches en {city} en el hotel {hotel} (o similar) {board}", en: "{nights} nights in {city} at {hotel} (or similar) {board}", ar: "{nights} ليالٍ في {city} في فندق {hotel} (أو ما شابه) {board}" },
//                 breakfastBoard: { es: "con desayuno incluido", en: "with breakfast included", ar: "شامل وجبة الإفطار" },
//                 fullBoard: { es: "con pensión completa", en: "with full board", ar: "شامل إقامة كاملة" },
//                 domesticFlights: { es: "Vuelos domésticos (Cairo-Lúxor/Asuán-Cairo)", en: "Domestic flights (Cairo-Luxor/Aswan-Cairo)", ar: "رحلات طيران داخلية (القاهرة-الأقصر/أسوان-القاهرة)" },
//             },
//             genericError: "Ocurrió un error. Por favor, inténtalo de nuevo.",
//             apiProcessingError: "Ocurrió un error al procesar tu solicitud. Por favor, intenta simplificar tu consulta o inténtalo de nuevo más tarde.",
//             quotaError: "Nuestro asistente de IA está experimentando una alta demanda en este momento. Por favor, inténtalo de nuevo en un momento.",
//             apiKeyError: "Hay un problema con la conexión a nuestro servicio de IA. Nuestro equipo ha sido notificado."
//         },
//         en: {
//             welcomeMessages: [
//                 "Welcome to Egiptura. Imagine the golden sun over the Pyramids as an expert guide reveals their secrets. I am your luxury travel advisor; what adventure have you dreamt of for Egypt?",
//                 "A warm greeting from the land of the pharaohs. At Egiptura, we design more than trips; we create legacies. Are you ready to start designing yours?",
//                 "Welcome. Picture the whisper of the Nile from the deck of a luxury cruise. That is the peace we offer. I am your personal counselor at Egiptura; how can we begin to chart your map?",
//             ],
//             tagline: "Your guide to the secrets of Egypt",
//             sendButton: "Send",
//             suggestions: [
//                 "I want an 8-day trip with a cruise",
//                 "What programs are available?",
//                 "Tell me about the Diamond category",
//                 "I need a custom trip",
//                 "Is it safe to travel to Egypt?",
//                 "Show me a short trip to Cairo",
//             ],
//             loadingMessages: [
//                 "Consulting the ancient papyri...",
//                 "Charting your course on the map of the pharaohs...",
//                 "Adding a touch of magic to your itinerary...",
//                 "Crafting a unique experience for you...",
//                 "Polishing the details of your next great adventure...",
//             ],
//             chatPlaceholder: "Write your query about Egypt...",
//             cardViewDetails: "View Details",
//             cardRequestQuote: "Request Quote",
//             cardSaveChanges: "Save Trip",
//             cardShare: "Share Trip",
//             cardLoadSaved: "Load Saved Trip",
//             cardNights: "nights",
//             cardDays: "days",
//             cardLabelDuration: "Days / Nights",
//             cardLabelCruiseNights: "Cruise Nights",
//             cardNightCruise: "night on cruise",
//             cardNightsCruise: "nights on cruise",
//             cardStart: "start",
//             cardGuide: "guide",
//             modalOverview: "Overview",
//             modalItinerary: "Itinerary",
//             modalAccommodation: "Accommodation",
//             modalPricing: "Pricing & Options",
//             modalIncluded: "Services Included",
//             modalExcluded: "Services Excluded",
//             modalImportantNotes: "Important Notes",
//             modalSelectCategory: "1. Select a category",
//             modalCategoryGold: "Gold Category",
//             modalCategoryGoldDesc: "5★ hotels and personalized service.",
//             modalCategoryDiamond: "Diamond Category",
//             modalCategoryDiamondDesc: "5★ Deluxe luxury and VIP experiences.",
//             modalPricesBySeason: "2. Prices by season",
//             modalSummerSeason: "Summer Season (May-Sep)",
//             modalWinterSeason: "Winter Season (Oct-Apr)",
//             modalPriceDouble: "Double Room",
//             modalPriceTriple: "Triple Room",
//             modalPriceSingle: "Single Room",
//             modalPerPerson: "per person",
//             modalItineraryOptions: "This program has multiple routes. Select an option:",
//             modalQuoteButton: "Request Quote",
//             modalContactButton: "Contact Agent",
//             modalExchangeRate: "Today's official exchange rate:",
//             modalExchangeRateDisclaimer: "Prices are in USD.",
//             modalDay: "Day",
//             modalCategory: "Category",
//             sampleAccommodations: "Sample Accommodations",
//             modalInfoDaysNights: "days / nights",
//             modalInfoStartIn: "Starts in",
//             modalInfoCruiseNights: "nights on cruise",
//             modalInfoCategories: "Categories",
//             customQuoteTitle: "Your Custom {duration}-Day Journey",
//             customQuoteCategory: "{category} Category",
//             customQuoteOverviewText: "An overview of your custom {duration}-day journey for {travelers} travelers, exploring the treasures of Egypt.",
//             customQuoteTabOverview: "Overview",
//             customQuoteTabItinerary: "Day-by-Day",
//             customQuoteTabPricing: "Pricing",
//             customQuoteCreated: "I have designed a trip especially for you! Here are all the details.",
//             totalGroupPriceLabel: "Total Group Price",
//             forTravelersLabel: "For {travelers} travelers",
//             pricePerPersonLabel: "Price Per Person",
//             averageLabel: "(average)",
//             // Fallback Generation Strings
//             fallbackDayTitles: {
//                 arrival: { es: "Llegada a El Cairo, la Tierra de los Faraones", en: "Arrival in Cairo, Land of the Pharaohs", ar: "الوصول إلى القاهرة، أرض الفراعنة" },
//                 cairoTour: { es: "Explorando los Tesoros de El Cairo", en: "Exploring the Treasures of Cairo", ar: "استكشاف كنوز القاهرة" },
//                 flyToCruise: { es: "Vuelo a Lúxor/Asuán e Inicio del Crucero", en: "Flight to Luxor/Aswan & Cruise Embarkation", ar: "رحلة طيران إلى الأقصر/أسوان وبدء الرحلة النيلية" },
//                 nileSailing: { es: "Navegando las Aguas Eternas del Nilo", en: "Sailing the Eternal Waters of the Nile", ar: "الإبحار في مياه النيل الخالدة" },
//                 returnToCairo: { es: "Regreso a la Vibrante Capital", en: "Return to the Vibrant Capital", ar: "العودة إلى العاصمة النابضة بالحياة" },
//                 departure: { es: "Salida de El Cairo con Recuerdos Inolvidables", en: "Departure from Cairo with Unforgettable Memories", ar: "المغادرة من القاهرة بذكريات لا تُنسى" },
//             },
//             fallbackDayActivities: {
//                 arrival: { es: "A tu llegada al Aeropuerto Internacional de El Cairo, nuestro representante te dará una cálida bienvenida y te ayudará con los trámites de visado. Luego, un traslado privado te llevará a tu hotel para que te instales y descanses. (Alojamiento con desayuno).", en: "Upon arrival at Cairo International Airport, our representative will give you a warm welcome and assist with visa procedures. Afterwards, a private transfer will take you to your hotel to check in and rest. (Accommodation with breakfast).", ar: "عند وصولك إلى مطار القاهرة الدولي، سيستقبلك ممثلنا بحفاوة ويساعدك في إجراءات التأشيرة. بعد ذلك، ستنقلك سيارة خاصة إلى فندقك لتسجيل الدخول والراحة. (إقامة مع وجبة الإفطار)." },
//                 cairoFreeDay: { es: "Desayuno en tu hotel. Hoy es un día para explorar a tu propio ritmo. Te sugerimos una visita opcional a {suggestions}. ¡Permítenos ayudarte a diseñar el día perfecto!", en: "Breakfast at your hotel. Today is a day to explore at your own pace. We suggest an optional visit to {suggestions}. Let us help you design the perfect day!", ar: "إفطار في فندقك. اليوم هو يوم للاستكشاف حسب رغبتك. نقترح زيارة اختيارية إلى {suggestions}. دعنا نساعدك في تصميم اليوم المثالي!" },
//                 flyToCruise: { es: "Desayuno en tu hotel de El Cairo. A la hora indicada, traslado al aeropuerto para tu vuelo a Lúxor o Asuán. Al llegar, embarcarás en tu crucero de lujo. Disfruta del almuerzo y la cena a bordo (Pensión completa).", en: "Breakfast at your Cairo hotel. At the designated time, transfer to the airport for your flight to Luxor or Aswan. Upon arrival, you will embark on your luxury cruise. Enjoy lunch and dinner on board (Full board).", ar: "إفطار في فندقك بالقاهرة. في الوقت المحدد، سيتم نقلك إلى المطار لرحلتك إلى الأقصر أو أسوان. عند الوصول، ستصعد على متن رحلتك النيلية الفاخرة. استمتع بالغداء والعشاء على متن السفينة (إقامة كاملة)." },
//                 nileSailing: { es: "Pensión completa a bordo. Hoy la navegación por el Nilo te revelará paisajes milenarios y templos majestuosos como Kom Ombo y Edfu, testigos silenciosos de la historia faraónica. Disfruta de las instalaciones del barco y de las vistas panorámicas.", en: "Full board on board. Today, sailing on the Nile will reveal ancient landscapes and majestic temples like Kom Ombo and Edfu, silent witnesses of pharaonic history. Enjoy the ship's facilities and panoramic views.", ar: "إقامة كاملة على متن السفينة. اليوم، سيكشف لك الإبحار في النيل عن مناظر طبيعية قديمة ومعابد مهيبة مثل كوم أمبو وإدفو، شهود صامتون على التاريخ الفرعوني. استمتع بمرافق السفينة والمناظر البانورامية." },
//                 returnToCairo: { es: "Después del desayuno en el crucero, desembarcarás y te trasladaremos al aeropuerto para tu vuelo de regreso a El Cairo. A tu llegada, traslado a tu hotel para tu última noche. (Alojamiento con desayuno).", en: "After breakfast on the cruise, you will disembark and we will transfer you to the airport for your flight back to Cairo. Upon arrival, transfer to your hotel for your final night. (Accommodation with breakfast).", ar: "بعد الإفطار على متن السفينة، ستنزل وسيتم نقلك إلى المطار لرحلتك العائدة إلى القاهرة. عند الوصول، سيتم نقلك إلى فندقك لليلة الأخيرة. (إقامة مع وجبة الإفطار)." },
//                 departure: { es: "Desayuno en tu hotel. A la hora acordada, nuestro representante te acompañará al Aeropuerto Internacional de El Cairo para tu vuelo de regreso, llevando contigo el alma de Egipto.", en: "Breakfast at your hotel. At the agreed time, our representative will escort you to Cairo International Airport for your return flight, taking the soul of Egypt with you.", ar: "إفطار في فندقك. في الوقت المتفق عليه، سيرافقك ممثلنا إلى مطار القاهرة الدولي لرحلة العودة، آخذاً معك روح مصر." },
//             },
//             optionalToursByCity: {
//                 cairo: { es: "el Museo de la Civilización Egipcia, el histórico Cairo Copto o un paseo en faluca por el Nilo", en: "the Museum of Egyptian Civilization, historic Coptic Cairo, or a felucca ride on the Nile", ar: "متحف الحضارة المصرية، القاهرة القبطية التاريخية، أو جولة بالفلوكة في النيل" },
//                 luxor: { es: "un vuelo en globo al amanecer sobre el Valle de los Reyes o el espectáculo de Luz y Sonido en el Templo de Karnak", en: "a sunrise hot air balloon ride over the Valley of the Kings or the Sound and Light show at Karnak Temple", ar: "رحلة بالمنطاد عند شروق الشمس فوق وادي الملوك أو عرض الصوت والضوء في معبد الكرنك" },
//                 aswan: { es: "el poblado Nubio para conocer su vibrante cultura, o los Jardines Botánicos en la Isla de Kitchener", en: "the Nubian village to experience its vibrant culture, or the Botanical Gardens on Kitchener's Island", ar: "القرية النوبية لتجربة ثقافتهم النابضة بالحياة، أو الحدائق النباتية في جزيرة كتشنر" },
//             },
//             serviceStrings: {
//                 accommodation: { es: "{nights} noches en {city} en el hotel {hotel} (o similar) {board}", en: "{nights} nights in {city} at {hotel} (or similar) {board}", ar: "{nights} ليالٍ في {city} في فندق {hotel} (أو ما شابه) {board}" },
//                 breakfastBoard: { es: "con desayuno incluido", en: "with breakfast included", ar: "شامل وجبة الإفطار" },
//                 fullBoard: { es: "con pensión completa", en: "with full board", ar: "شامل إقامة كاملة" },
//                 domesticFlights: { es: "Vuelos domésticos (Cairo-Lúxor/Asuán-Cairo)", en: "Domestic flights (Cairo-Luxor/Aswan-Cairo)", ar: "رحلات طيران داخلية (القاهرة-الأقصر/أسوان-القاهرة)" },
//             },
//             genericError: "An error occurred. Please try again.",
//             apiProcessingError: "An error occurred while processing your request. Please try to simplify your query or try again later.",
//             quotaError: "Our AI assistant is currently experiencing high demand. Please try again in a little while.",
//             apiKeyError: "There's an issue with the connection to our AI service. Our team has been notified."
//         },
//         ar: {
//             welcomeMessages: [
//                 "أهلاً بك في إيجيبتورا. تخيل شروق الشمس الذهبي فوق الأهرامات بينما يشرح لك مرشد خبير أسرارها. أنا مستشارك للسفر الفاخر، فما هي المغامرة التي حلمت بها في مصر؟",
//                 "تحية حارة من أرض الفراعنة. في إيجيبتورا، نحن لا نصمم رحلات فحسب، بل نصنع إرثًا. هل أنت مستعد لبدء تصميم إرثك؟",
//                 "أهلاً بك. فكر في همس النيل من على سطح سفينة فاخرة. هذا هو السلام الذي نقدمه. أنا مستشارك الشخصي في إيجيبتورا، كيف يمكننا البدء في رسم خريطتك؟",
//             ],
//             tagline: "دليلك إلى أسرار مصر",
//             sendButton: "إرسال",
//             suggestions: [
//                 "أريد رحلة لمدة 8 أيام مع رحلة نيلية",
//                 "ما هي البرامج المتاحة؟",
//                 "أخبرني عن الفئة الماسية",
//                 "أحتاج إلى رحلة مخصصة",
//                 "هل السفر إلى مصر آمن؟",
//                 "أرني رحلة قصيرة إلى القاهرة",
//             ],
//             loadingMessages: [
//                 "جاري استشارة البرديات القديمة...",
//                 "جاري رسم مسارك على خريطة الفراعنة...",
//                 "جاري إضافة لمسة من السحر إلى خط سير رحلتك...",
//                 "جاري تصميم تجربة فريدة لك...",
//                 "جاري وضع اللمسات الأخيرة على مغامرتك الكبرى التالية...",
//             ],
//             chatPlaceholder: "اكتب استفسارك عن مصر...",
//             cardViewDetails: "عرض التفاصيل",
//             cardRequestQuote: "طلب عرض سعر",
//             cardSaveChanges: "حفظ الرحلة",
//             cardShare: "مشاركة الرحلة",
//             cardLoadSaved: "تحميل الرحلة المحفوظة",
//             cardNights: "ليالٍ",
//             cardDays: "أيام",
//             cardLabelDuration: "أيام / ليالي",
//             cardLabelCruiseNights: "ليالي الكروز",
//             cardNightCruise: "ليلة في الكروز",
//             cardNightsCruise: "ليالٍ في الكروز",
//             cardStart: "البداية",
//             cardGuide: "مرشد",
//             modalOverview: "نظرة عامة",
//             modalItinerary: "خط سير الرحلة",
//             modalAccommodation: "الإقامة",
//             modalPricing: "الأسعار والخيارات",
//             modalIncluded: "الخدمات المتضمنة",
//             modalExcluded: "الخدمات غير المتضمنة",
//             modalImportantNotes: "ملاحظات هامة",
//             modalSelectCategory: "1. اختر فئة",
//             modalCategoryGold: "الفئة الذهبية",
//             modalCategoryGoldDesc: "فنادق 5 نجوم وخدمة شخصية.",
//             modalCategoryDiamond: "الفئة الماسية",
//             modalCategoryDiamondDesc: "فنادق 5 نجوم ديلوكس وتجارب لكبار الشخصيات.",
//             modalPricesBySeason: "2. الأسعار حسب الموسم",
//             modalSummerSeason: "موسم الصيف (مايو-سبتمبر)",
//             modalWinterSeason: "موسم الشتاء (أكتوبر-أبريل)",
//             modalPriceDouble: "غرفة مزدوجة",
//             modalPriceTriple: "غرفة ثلاثية",
//             modalPriceSingle: "غرفة فردية",
//             modalPerPerson: "للشخص الواحد",
//             modalItineraryOptions: "هذا البرنامج له مسارات متعددة. اختر خيارًا:",
//             modalQuoteButton: "طلب عرض سعر",
//             modalContactButton: "اتصل بالوكيل",
//             modalExchangeRate: "سعر الصرف الرسمي اليوم:",
//             modalExchangeRateDisclaimer: "الأسعار بالدولار الأمريكي.",
//             modalDay: "اليوم",
//             modalCategory: "الفئة",
//             sampleAccommodations: "أمثلة على أماكن الإقامة",
//             modalInfoDaysNights: "أيام / ليالي",
//             modalInfoStartIn: "يبدأ في",
//             modalInfoCruiseNights: "ليالٍ في الكروز",
//             modalInfoCategories: "الفئات",
//             customQuoteTitle: "رحلتك المخصصة لمدة {duration} يومًا",
//             customQuoteCategory: "فئة {category}",
//             customQuoteOverviewText: "نظرة عامة على رحلتك المخصصة لمدة {duration} يومًا لـ {travelers} مسافر، لاستكشاف كنوز مصر.",
//             customQuoteTabOverview: "نظرة عامة",
//             customQuoteTabItinerary: "يوم بيوم",
//             customQuoteTabPricing: "الأسعار",
//             customQuoteCreated: "لقد صممت رحلة خاصة لك! إليك كل التفاصيل.",
//             totalGroupPriceLabel: "السعر الإجمالي للمجموعة",
//             forTravelersLabel: "لـ {travelers} مسافرين",
//             pricePerPersonLabel: "السعر للشخص الواحد",
//             averageLabel: "(متوسط)",
//             fallbackDayTitles: {
//                 arrival: { es: "Llegada a El Cairo, la Tierra de los Faraones", en: "Arrival in Cairo, Land of the Pharaohs", ar: "الوصول إلى القاهرة، أرض الفراعنة" },
//                 cairoTour: { es: "Explorando los Tesoros de El Cairo", en: "Exploring the Treasures of Cairo", ar: "استكشاف كنوز القاهرة" },
//                 flyToCruise: { es: "Vuelo a Lúxor/Asuán e Inicio del Crucero", en: "Flight to Luxor/Aswan & Cruise Embarkation", ar: "رحلة طيران إلى الأقصر/أسوان وبدء الرحلة النيلية" },
//                 nileSailing: { es: "Navegando las Aguas Eternas del Nilo", en: "Sailing the Eternal Waters of the Nile", ar: "الإبحار في مياه النيل الخالدة" },
//                 returnToCairo: { es: "Regreso a la Vibrante Capital", en: "Return to the Vibrant Capital", ar: "العودة إلى العاصمة النابضة بالحياة" },
//                 departure: { es: "Salida de El Cairo con Recuerdos Inolvidables", en: "Departure from Cairo with Unforgettable Memories", ar: "المغادرة من القاهرة بذكريات لا تُنسى" },
//             },
//             fallbackDayActivities: {
//                 arrival: { es: "A tu llegada al Aeropuerto Internacional de El Cairo, nuestro representante te dará una cálida bienvenida y te ayudará con los trámites de visado. Luego, un traslado privado te llevará a tu hotel para que te instales y descanses. (Alojamiento con desayuno).", en: "Upon arrival at Cairo International Airport, our representative will give you a warm welcome and assist with visa procedures. Afterwards, a private transfer will take you to your hotel to check in and rest. (Accommodation with breakfast).", ar: "عند وصولك إلى مطار القاهرة الدولي، سيستقبلك ممثلنا بحفاوة ويساعدك في إجراءات التأشيرة. بعد ذلك، ستنقلك سيارة خاصة إلى فندقك لتسجيل الدخول والراحة. (إقامة مع وجبة الإفطار)." },
//                 cairoFreeDay: { es: "Desayuno en tu hotel. Hoy es un día para explorar a tu propio ritmo. Te sugerimos una visita opcional a {suggestions}. ¡Permítenos ayudarte a diseñar el día perfecto!", en: "Breakfast at your hotel. Today is a day to explore at your own pace. We suggest an optional visit to {suggestions}. Let us help you design the perfect day!", ar: "إفطار في فندقك. اليوم هو يوم للاستكشاف حسب رغبتك. نقترح زيارة اختيارية إلى {suggestions}. دعنا نساعدك في تصميم اليوم المثالي!" },
//                 flyToCruise: { es: "Desayuno en tu hotel de El Cairo. A la hora indicada, traslado al aeropuerto para tu vuelo a Lúxor o Asuán. Al llegar, embarcarás en tu crucero de lujo. Disfruta del almuerzo y la cena a bordo (Pensión completa).", en: "Breakfast at your Cairo hotel. At the designated time, transfer to the airport for your flight to Luxor or Aswan. Upon arrival, you will embark on your luxury cruise. Enjoy lunch and dinner on board (Full board).", ar: "إفطار في فندقك بالقاهرة. في الوقت المحدد، سيتم نقلك إلى المطار لرحلتك إلى الأقصر أو أسوان. عند الوصول، ستصعد على متن رحلتك النيلية الفاخرة. استمتع بالغداء والعشاء على متن السفينة (إقامة كاملة)." },
//                 nileSailing: { es: "Pensión completa a bordo. Hoy la navegación por el Nilo te revelará paisajes milenarios y templos majestuosos como Kom Ombo y Edfu, testigos silenciosos de la historia faraónica. Disfruta de las instalaciones del barco y de las vistas panorámicas.", en: "Full board on board. Today, sailing on the Nile will reveal ancient landscapes and majestic temples like Kom Ombo and Edfu, silent witnesses of pharaonic history. Enjoy the ship's facilities and panoramic views.", ar: "إقامة كاملة على متن السفينة. اليوم، سيكشف لك الإبحار في النيل عن مناظر طبيعية قديمة ومعابد مهيبة مثل كوم أمبو وإدفو، شهود صامتون على التاريخ الفرعوني. استمتع بمرافق السفينة والمناظر البانورامية." },
//                 returnToCairo: { es: "Después del desayuno en el crucero, desembarcarás y te trasladaremos al aeropuerto para tu vuelo de regreso a El Cairo. A tu llegada, traslado a tu hotel para tu última noche. (Alojamiento con desayuno).", en: "After breakfast on the cruise, you will disembark and we will transfer you to the airport for your flight back to Cairo. Upon arrival, transfer to your hotel for your final night. (Accommodation with breakfast).", ar: "بعد الإفطار على متن السفينة، ستنزل وسيتم نقلك إلى المطار لرحلتك العائدة إلى القاهرة. عند الوصول، سيتم نقلك إلى فندقك لليلة الأخيرة. (إقامة مع وجبة الإفطار)." },
//                 departure: { es: "Desayuno en tu hotel. A la hora acordada, nuestro representante te acompañará al Aeropuerto Internacional de El Cairo para tu vuelo de regreso, llevando contigo el alma de Egipto.", en: "Breakfast at your hotel. At the agreed time, our representative will escort you to Cairo International Airport for your return flight, taking the soul of Egypt with you.", ar: "إفطار في فندقك. في الوقت المتفق عليه، سيرافقك ممثلنا إلى مطار القاهرة الدولي لرحلة العودة، آخذاً معك روح مصر." },
//             },
//             optionalToursByCity: {
//                 cairo: { es: "el Museo de la Civilización Egipcia, el histórico Cairo Copto o un paseo en faluca por el Nilo", en: "the Museum of Egyptian Civilization, historic Coptic Cairo, or a felucca ride on the Nile", ar: "متحف الحضارة المصرية، القاهرة القبطية التاريخية، أو جولة بالفلوكة في النيل" },
//                 luxor: { es: "un vuelo en globo al amanecer sobre el Valle de los Reyes o el espectáculo de Luz y Sonido en el Templo de Karnak", en: "a sunrise hot air balloon ride over the Valley of the Kings or the Sound and Light show at Karnak Temple", ar: "رحلة بالمنطاد عند شروق الشمس فوق وادي الملوك أو عرض الصوت والضوء في معبد الكرنك" },
//                 aswan: { es: "el poblado Nubio para conocer su vibrante cultura, o los Jardines Botánicos en la Isla de Kitchener", en: "the Nubian village to experience its vibrant culture, or the Botanical Gardens on Kitchener's Island", ar: "القرية النوبية لتجربة ثقافتهم النابضة بالحياة، أو الحدائق النباتية في جزيرة كتشنر" },
//             },
//             serviceStrings: {
//                 accommodation: { es: "{nights} noches en {city} en el hotel {hotel} (o similar) {board}", en: "{nights} nights in {city} at {hotel} (or similar) {board}", ar: "{nights} ليالٍ في {city} في فندق {hotel} (أو ما شابه) {board}" },
//                 breakfastBoard: { es: "con desayuno incluido", en: "with breakfast included", ar: "شامل وجبة الإفطار" },
//                 fullBoard: { es: "con pensión completa", en: "with full board", ar: "شامل إقامة كاملة" },
//                 domesticFlights: { es: "Vuelos domésticos (Cairo-Lúxor/Asuán-Cairo)", en: "Domestic flights (Cairo-Luxor/Aswan-Cairo)", ar: "رحلات طيران داخلية (القاهرة-الأقصر/أسوان-القاهرة)" },
//             },
//             genericError: "حدث خطأ. يرجى المحاولة مرة أخرى.",
//             apiProcessingError: "حدث خطأ أثناء معالجة طلبك. يرجى محاولة تبسيط استفسارك أو المحاولة مرة أخرى لاحقًا.",
//             quotaError: "مساعدنا الرقمي يواجه حاليًا طلبًا مرتفعًا. يرجى المحاولة مرة أخرى بعد قليل.",
//             apiKeyError: "هناك مشكلة في الاتصال بخدمة الذكاء الاصطناعي لدينا. تم إخطار فريقنا."
//         }
//     }
// };





export const localizedStrings = {
    duration: {
        es: "{days} días / {nights} noches",
        en: "{days} days / {nights} nights",
        ar: "{days} أيام / {nights} ليالٍ"
    },
    askForCategory: {
        es: "¡Excelente elección! Para darte el precio exacto, ¿prefieres la categoría Gold o la categoría Diamond para tu viaje?",
        en: "Excellent choice! To give you the exact price, do you prefer the Gold or Diamond category for your trip?",
        ar: "اختيار ممتاز! لإعطائك السعر الدقيق، هل تفضل فئة الذهب أم فئة الألماس لرحلتك؟"
    },
    pricePerPerson: {
        es: "Precio por persona en",
        en: "Price per person in",
        ar: "السعر للشخص الواحد في"
    },
    double: { es: "habitación doble", en: "double room", ar: "غرفة مزدوجة" },
    triple: { es: "habitación triple", en: "triple room", ar: "غرفة ثلاثية" },
    single: { es: "habitación single", en: "single room", ar: "غرفة فردية" },
    summer: { es: "Temporada de Verano (Mayo-Sept)", en: "Summer Season (May-Sept)", ar: "موسم الصيف (مايو-سبتمبر)" },
    winter: { es: "Temporada de Invierno (Oct-Abr)", en: "Winter Season (Oct-Apr)", ar: "موسم الشتاء (أكتوبر-أبريل)" },
    seasonalDisclaimer: {
        es: "Estos precios son orientativos y pueden variar ligeramente según la fecha exacta del viaje.",
        en: "These prices are estimates and may vary slightly depending on the exact travel date.",
        ar: "هذه الأسعار تقديرية وقد تختلف قليلاً حسب تاريخ السفر الدقيق."
    },
    diversifiedCtas: {
      es: [
        "¿Te gustaría que te envíe el itinerario detallado de este programa?",
        "¿Quieres que te muestre los hoteles de lujo que incluye este viaje?",
        "Si este programa te inspira, puedo contarte más sobre las experiencias únicas que incluye.",
        "¿Hay algo más que te gustaría saber sobre este viaje ancestral?",
        "Puedo explicarte qué servicios exclusivos hacen de este programa una experiencia inolvidable. ¿Te interesa?"
      ],
      en: [
        "Would you like me to send you the detailed itinerary for this program?",
        "Do you want me to show you the luxury hotels included in this trip?",
        "If this program inspires you, I can tell you more about the unique experiences it includes.",
        "Is there anything else you would like to know about this ancestral journey?",
        "I can explain the exclusive services that make this program an unforgettable experience. Are you interested?"
      ],
      ar: [
        "هل تود أن أرسل لك خط سير الرحلة المفصل لهذا البرنامج؟",
        "هل تريد أن أريك الفنادق الفاخرة التي تشملها هذه الرحلة؟",
        "إذا كان هذا البرنامج يلهمك، يمكنني أن أخبرك المزيد عن التجارب الفريدة التي يتضمنها.",
        "هل هناك أي شيء آخر تود معرفته عن هذه الرحلة القديمة؟",
        "يمكنني أن أشرح لك الخدمات الحصرية التي تجعل هذا البرنامج تجربة لا تُنسى. هل أنت مهتم؟"
      ]
    },
    ui: {
        es: {
            welcomeMessages: [
                "Bienvenido a Egiptura. Imagina el sol dorado sobre las Pirámides mientras un guía experto te revela sus secretos. Soy tu asesor de viajes de lujo, ¿qué aventura soñaste para Egipto?",
                "Un cordial saludo desde la tierra de los faraones. En Egiptura, diseñamos más que viajes; creamos legados. ¿Estás listo para empezar a diseñar el tuyo?",
                "Bienvenido. Piensa en el murmullo del Nilo desde la cubierta de un crucero de lujo. Esa es la paz que ofrecemos. Soy tu consejero personal en Egiptura, ¿cómo podemos empezar a trazar tu mapa?",
            ],
            tagline: "Tu guía a los secretos de Egipto",
            sendButton: "Enviar",
            suggestions: [
                "Quiero un viaje de 8 días con crucero",
                "¿Qué programas tenéis disponibles?",
                "Háblame sobre la categoría Diamond",
                "Necesito un viaje a medida",
                "¿Es seguro viajar a Egipto?",
                "Muéstrame un viaje corto a El Cairo",
            ],
            loadingMessages: [
                "Consultando los antiguos papiros...",
                "Trazando tu ruta en el mapa de los faraones...",
                "Añadiendo un toque de magia a tu itinerario...",
                "Diseñando una experiencia única para ti...",
                "Puliendo los detalles de tu próxima gran aventura...",
            ],
            chatPlaceholder: "Escribe tu consulta sobre Egipto...",
            cardViewDetails: "Ver detalles",
            cardRequestQuote: "Solicitar cotización",
            cardSaveChanges: "Guardar Viaje",
            cardShare: "Compartir Viaje",
            cardLoadSaved: "Cargar Viaje Guardado",
            cardNights: "noches",
            cardDays: "días",
            cardLabelDuration: "Días / Noches",
            cardLabelCruiseNights: "Noches Crucero",
            cardNightCruise: "noche en crucero",
            cardNightsCruise: "noches en crucero",
            cardStart: "inicio",
            cardGuide: "guía",
            modalOverview: "Resumen",
            modalItinerary: "Itinerario",
            modalAccommodation: "Alojamiento",
            modalPricing: "Precios y Opciones",
            modalIncluded: "Servicios Incluidos",
            modalExcluded: "Servicios Excluidos",
            modalImportantNotes: "Notas Importantes",
            modalSelectCategory: "1. Selecciona una categoría",
            modalCategoryGold: "Categoría Gold",
            modalCategoryGoldDesc: "Hoteles 5★ y servicio personalizado.",
            modalCategoryDiamond: "Categoría Diamond",
            modalCategoryDiamondDesc: "Lujo 5★ Deluxe y experiencias VIP.",
            modalPricesBySeason: "2. Precios por temporada",
            modalSummerSeason: "Temporada de Verano (Mayo-Sept)",
            modalWinterSeason: "Temporada de Invierno (Oct-Abr)",
            modalPriceDouble: "Habitación Doble",
            modalPriceTriple: "Habitación Triple",
            modalPriceSingle: "Habitación Individual",
            modalPerPerson: "por persona",
            modalItineraryOptions: "Este programa tiene múltiples rutas. Selecciona una opción:",
            modalQuoteButton: "Solicitar Cotización",
            modalContactButton: "Contactar Agente",
            modalExchangeRate: "Tipo de cambio oficial hoy:",
            modalExchangeRateDisclaimer: "Los precios son en USD.",
            modalDay: "Día",
            modalCategory: "Categoría",
            sampleAccommodations: "Alojamientos de Muestra",
            modalInfoDaysNights: "días / noches",
            modalInfoStartIn: "Inicia en",
            modalInfoCruiseNights: "noches en crucero",
            modalInfoCategories: "Categorías",
            customQuoteTitle: "Tu Viaje Personalizado de {duration} Días",
            customQuoteCategory: "Categoría {category}",
            customQuoteOverviewText: "Un resumen de su viaje personalizado de {duration} días para {travelers} viajeros, explorando los tesoros de Egipto.",
            customQuoteTabOverview: "Resumen",
            customQuoteTabItinerary: "Día a Día",
            customQuoteTabPricing: "Precios",
            customQuoteCreated: "¡He diseñado un viaje especialmente para ti! Aquí tienes todos los detalles.",
            totalGroupPriceLabel: "Precio Total del Grupo",
            forTravelersLabel: "Para {travelers} viajeros",
            pricePerPersonLabel: "Precio Por Persona",
            averageLabel: "(promedio)",
            
            // النصوص الجديدة المضافة هنا
            modalNights: 'Noches',
            modalNoAccommodation: 'No hay información de alojamiento disponible',
            modalProgramDescription: 'Descripción del Programa',
            modalCustomProgramDetails: 'Detalles del Programa Personalizado',
            modalTravelers: 'Viajeros',
            modalSeason: 'Temporada',
            modalDuration: 'Duración',
            modalDays: 'días',
            
            // Fallback Generation Strings
            fallbackDayTitles: {
                arrival: { es: "Llegada a El Cairo, la Tierra de los Faraones", en: "Arrival in Cairo, Land of the Pharaohs", ar: "الوصول إلى القاهرة، أرض الفراعنة" },
                cairoTour: { es: "Explorando los Tesoros de El Cairo", en: "Exploring the Treasures of Cairo", ar: "استكشاف كنوز القاهرة" },
                flyToCruise: { es: "Vuelo a Lúxor/Asuán e Inicio del Crucero", en: "Flight to Luxor/Aswan & Cruise Embarkation", ar: "رحلة طيران إلى الأقصر/أسوان وبدء الرحلة النيلية" },
                nileSailing: { es: "Navegando las Aguas Eternas del Nilo", en: "Sailing the Eternal Waters of the Nile", ar: "الإبحار في مياه النيل الخالدة" },
                returnToCairo: { es: "Regreso a la Vibrante Capital", en: "Return to the Vibrant Capital", ar: "العودة إلى العاصمة النابضة بالحياة" },
                departure: { es: "Salida de El Cairo con Recuerdos Inolvidables", en: "Departure from Cairo with Unforgettable Memories", ar: "المغادرة من القاهرة بذكريات لا تُنسى" },
            },
            fallbackDayActivities: {
                arrival: {
                    en: ["Upon arrival at Cairo International Airport, our representative will give you a warm welcome and assist with visa procedures. Afterwards, a private transfer will take you to your hotel to check in and rest. (Accommodation with breakfast)."],
                    es: ["A tu llegada al Aeropuerto Internacional de El Cairo, nuestro representante te dará una cálida bienvenida y te ayudará con los trámites de visado. Luego, un traslado privado te llevará a tu hotel para que te instales y descanses. (Alojamiento con desayuno)."],
                    ar: ["عند وصولك إلى مطار القاهرة الدولي، سيستقبلك ممثلنا بحفاوة ويساعدك في إجراءات التأشيرة. بعد ذلك، ستنقلك سيارة خاصة إلى فندقك لتسجيل الدخول والراحة. (إقامة مع وجبة الإفطار)."]
                },
                cairoFreeDay: {
                    en: [
                    "Breakfast at your hotel. Visit the Egyptian Museum and the Great Pyramids of Giza.",
                    "Breakfast at your hotel. Explore Islamic Cairo and Khan El Khalili Bazaar.",
                    "Breakfast at your hotel. Enjoy a full-day optional tour to Memphis and Saqqara."
                    ],
                    es: [
                    "Desayuno en tu hotel. Visita el Museo Egipcio y las Grandes Pirámides de Guiza.",
                    "Desayuno en tu hotel. Explora El Cairo Islámico y el bazar Khan El Khalili.",
                    "Desayuno en tu hotel. Excursión opcional de día completo a Menfis y Saqqara."
                    ],
                    ar: [
                    "إفطار في فندقك. زيارة المتحف المصري والأهرامات الكبرى بالجيزة.",
                    "إفطار في فندقك. استكشاف القاهرة الإسلامية وخان الخليلي.",
                    "إفطار في فندقك. جولة اختيارية ليوم كامل إلى ممفيس وسقارة."
                    ]
                },
                flyToCruise: {
                    en: ["Breakfast at your Cairo hotel. Flight to Luxor or Aswan and embark your luxury Nile cruise. Enjoy lunch and dinner on board (Full board)."],
                    es: ["Desayuno en tu hotel de El Cairo. Vuelo a Lúxor o Asuán y embarque en tu crucero de lujo. Disfruta del almuerzo y la cena a bordo (Pensión completa)."],
                    ar: ["إفطار في فندقك بالقاهرة. رحلة طيران إلى الأقصر أو أسوان وبدء الرحلة النيلية. استمتع بالغداء والعشاء على متن السفينة (إقامة كاملة)."]
                },
                nileSailing: {
                    en: [
                    "Sail to Edfu and visit the Temple of Horus.",
                    "Continue to Kom Ombo to explore the twin temples of Sobek and Haroeris.",
                    "Enjoy the beauty of the Nile while relaxing on board and watching rural life pass by."
                    ],
                    es: [
                    "Navega a Edfu y visita el Templo de Horus.",
                    "Continúa hacia Kom Ombo para explorar los templos gemelos de Sobek y Haroeris.",
                    "Disfruta de la belleza del Nilo mientras te relajas a bordo observando la vida rural."
                    ],
                    ar: [
                    "الإبحار إلى إدفو وزيارة معبد حورس.",
                    "مواصلة الرحلة إلى كوم أمبو لاستكشاف المعبدين التوأمين للإله سوبك وحوروريس.",
                    "استمتع بجمال النيل أثناء الاسترخاء على متن السفينة ومشاهدة الحياة الريفية تمر بجانبك."
                    ]
                },
                returnToCairo: {
                    en: ["After breakfast, disembark and fly back to Cairo. Transfer to your hotel for your final night."],
                    es: ["Después del desayuno, desembarca y vuela de regreso a El Cairo. Traslado a tu hotel para tu última noche."],
                    ar: ["بعد الإفطار، النزول من السفينة والعودة إلى القاهرة. الانتقال إلى الفندق لليلة الأخيرة."]
                },
                departure: {
                    en: ["Breakfast at your hotel. Transfer to Cairo International Airport for your return flight."],
                    es: ["Desayuno en tu hotel. Traslado al Aeropuerto Internacional de El Cairo para tu vuelo de regreso."],
                    ar: ["إفطار في فندقك. الانتقال إلى مطار القاهرة الدولي لرحلة العودة."]
                }
                },

            optionalToursByCity: {
                cairo: { es: "el Museo de la Civilización Egipcia, el histórico Cairo Copto o un paseo en faluca por el Nilo", en: "the Museum of Egyptian Civilization, historic Coptic Cairo, or a felucca ride on the Nile", ar: "متحف الحضارة المصرية، القاهرة القبطية التاريخية، أو جولة بالفلوكة في النيل" },
                luxor: { es: "un vuelo en globo al amanecer sobre el Valle de los Reyes o el espectáculo de Luz y Sonido en el Templo de Karnak", en: "a sunrise hot air balloon ride over the Valley of the Kings or the Sound and Light show at Karnak Temple", ar: "رحلة بالمنطاد عند شروق الشمس فوق وادي الملوك أو عرض الصوت والضوء في معبد الكرنك" },
                aswan: { es: "el poblado Nubio para conocer su vibrante cultura, o los Jardines Botánicos en la Isla de Kitchener", en: "the Nubian village to experience its vibrant culture, or the Botanical Gardens on Kitchener's Island", ar: "القرية النوبية لتجربة ثقافتهم النابضة بالحياة، أو الحدائق النباتية في جزيرة كتشنر" },
            },
            serviceStrings: {
                accommodation: { es: "{nights} noches en {city} en el hotel {hotel} (o similar) {board}", en: "{nights} nights in {city} at {hotel} (or similar) {board}", ar: "{nights} ليالٍ في {city} في فندق {hotel} (أو ما شابه) {board}" },
                breakfastBoard: { es: "con desayuno incluido", en: "with breakfast included", ar: "شامل وجبة الإفطار" },
                fullBoard: { es: "con pensión completa", en: "with full board", ar: "شامل إقامة كاملة" },
                domesticFlights: { es: "Vuelos domésticos (Cairo-Lúxor/Asuán-Cairo)", en: "Domestic flights (Cairo-Luxor/Aswan-Cairo)", ar: "رحلات طيران داخلية (القاهرة-الأقصر/أسوان-القاهرة)" },
            },
            genericError: "Ocurrió un error. Por favor, inténtalo de nuevo.",
            apiProcessingError: "Ocurrió un error al procesar tu solicitud. Por favor, intenta simplificar tu consulta o inténtalo de nuevo más tarde.",
            quotaError: "Nuestro asistente de IA está experimentando una alta demanda en este momento. Por favor, inténtalo de nuevo en un momento.",
            apiKeyError: "Hay un problema con la conexión a nuestro servicio de IA. Nuestro equipo ha sido notificado."
        },
        en: {
            welcomeMessages: [
                "Welcome to Egiptura. Imagine the golden sun over the Pyramids as an expert guide reveals their secrets. I am your luxury travel advisor; what adventure have you dreamt of for Egypt?",
                "A warm greeting from the land of the pharaohs. At Egiptura, we design more than trips; we create legacies. Are you ready to start designing yours?",
                "Welcome. Picture the whisper of the Nile from the deck of a luxury cruise. That is the peace we offer. I am your personal counselor at Egiptura; how can we begin to chart your map?",
            ],
            tagline: "Your guide to the secrets of Egypt",
            sendButton: "Send",
            suggestions: [
                "I want an 8-day trip with a cruise",
                "What programs are available?",
                "Tell me about the Diamond category",
                "I need a custom trip",
                "Is it safe to travel to Egypt?",
                "Show me a short trip to Cairo",
            ],
            loadingMessages: [
                "Consulting the ancient papyri...",
                "Charting your course on the map of the pharaohs...",
                "Adding a touch of magic to your itinerary...",
                "Crafting a unique experience for you...",
                "Polishing the details of your next great adventure...",
            ],
            chatPlaceholder: "Write your query about Egypt...",
            cardViewDetails: "View Details",
            cardRequestQuote: "Request Quote",
            cardSaveChanges: "Save Trip",
            cardShare: "Share Trip",
            cardLoadSaved: "Load Saved Trip",
            cardNights: "nights",
            cardDays: "days",
            cardLabelDuration: "Days / Nights",
            cardLabelCruiseNights: "Cruise Nights",
            cardNightCruise: "night on cruise",
            cardNightsCruise: "nights on cruise",
            cardStart: "start",
            cardGuide: "guide",
            modalOverview: "Overview",
            modalItinerary: "Itinerary",
            modalAccommodation: "Accommodation",
            modalPricing: "Pricing & Options",
            modalIncluded: "Services Included",
            modalExcluded: "Services Excluded",
            modalImportantNotes: "Important Notes",
            modalSelectCategory: "1. Select a category",
            modalCategoryGold: "Gold Category",
            modalCategoryGoldDesc: "5★ hotels and personalized service.",
            modalCategoryDiamond: "Diamond Category",
            modalCategoryDiamondDesc: "5★ Deluxe luxury and VIP experiences.",
            modalPricesBySeason: "2. Prices by season",
            modalSummerSeason: "Summer Season (May-Sep)",
            modalWinterSeason: "Winter Season (Oct-Apr)",
            modalPriceDouble: "Double Room",
            modalPriceTriple: "Triple Room",
            modalPriceSingle: "Single Room",
            modalPerPerson: "per person",
            modalItineraryOptions: "This program has multiple routes. Select an option:",
            modalQuoteButton: "Request Quote",
            modalContactButton: "Contact Agent",
            modalExchangeRate: "Today's official exchange rate:",
            modalExchangeRateDisclaimer: "Prices are in USD.",
            modalDay: "Day",
            modalCategory: "Category",
            sampleAccommodations: "Sample Accommodations",
            modalInfoDaysNights: "days / nights",
            modalInfoStartIn: "Starts in",
            modalInfoCruiseNights: "nights on cruise",
            modalInfoCategories: "Categories",
            customQuoteTitle: "Your Custom {duration}-Day Journey",
            customQuoteCategory: "{category} Category",
            customQuoteOverviewText: "An overview of your custom {duration}-day journey for {travelers} travelers, exploring the treasures of Egypt.",
            customQuoteTabOverview: "Overview",
            customQuoteTabItinerary: "Day-by-Day",
            customQuoteTabPricing: "Pricing",
            customQuoteCreated: "I have designed a trip especially for you! Here are all the details.",
            totalGroupPriceLabel: "Total Group Price",
            forTravelersLabel: "For {travelers} travelers",
            pricePerPersonLabel: "Price Per Person",
            averageLabel: "(average)",
            
            // النصوص الجديدة المضافة هنا
            modalNights: 'Nights',
            modalNoAccommodation: 'No accommodation information available',
            modalProgramDescription: 'Program Description',
            modalCustomProgramDetails: 'Custom Program Details',
            modalTravelers: 'Travelers',
            modalSeason: 'Season',
            modalDuration: 'Duration',
            modalDays: 'days',
            
            // Fallback Generation Strings
            fallbackDayTitles: {
                arrival: { es: "Llegada a El Cairo, la Tierra de los Faraones", en: "Arrival in Cairo, Land of the Pharaohs", ar: "الوصول إلى القاهرة، أرض الفراعنة" },
                cairoTour: { es: "Explorando los Tesoros de El Cairo", en: "Exploring the Treasures of Cairo", ar: "استكشاف كنوز القاهرة" },
                flyToCruise: { es: "Vuelo a Lúxor/Asuán e Inicio del Crucero", en: "Flight to Luxor/Aswan & Cruise Embarkation", ar: "رحلة طيران إلى الأقصر/أسوان وبدء الرحلة النيلية" },
                nileSailing: { es: "Navegando las Aguas Eternas del Nilo", en: "Sailing the Eternal Waters of the Nile", ar: "الإبحار في مياه النيل الخالدة" },
                returnToCairo: { es: "Regreso a la Vibrante Capital", en: "Return to the Vibrant Capital", ar: "العودة إلى العاصمة النابضة بالحياة" },
                departure: { es: "Salida de El Cairo con Recuerdos Inolvidables", en: "Departure from Cairo with Unforgettable Memories", ar: "المغادرة من القاهرة بذكريات لا تُنسى" },
            },
            fallbackDayActivities: {
                arrival: { es: "A tu llegada al Aeropuerto Internacional de El Cairo, nuestro representante te dará una cálida bienvenida y te ayudará con los trámites de visado. Luego, un traslado privado te llevará a tu hotel para que te instales y descanses. (Alojamiento con desayuno).", en: "Upon arrival at Cairo International Airport, our representative will give you a warm welcome and assist with visa procedures. Afterwards, a private transfer will take you to your hotel to check in and rest. (Accommodation with breakfast).", ar: "عند وصولك إلى مطار القاهرة الدولي، سيستقبلك ممثلنا بحفاوة ويساعدك في إجراءات التأشيرة. بعد ذلك، ستنقلك سيارة خاصة إلى فندقك لتسجيل الدخول والراحة. (إقامة مع وجبة الإفطار)." },
                cairoFreeDay: { es: "Desayuno en tu hotel. Hoy es un día para explorar a tu propio ritmo. Te sugerimos una visita opcional a {suggestions}. ¡Permítenos ayudarte a diseñar el día perfecto!", en: "Breakfast at your hotel. Today is a day to explore at your own pace. We suggest an optional visit to {suggestions}. Let us help you design the perfect day!", ar: "إفطار في فندقك. اليوم هو يوم للاستكشاف حسب رغبتك. نقترح زيارة اختيارية إلى {suggestions}. دعنا نساعدك في تصميم اليوم المثالي!" },
                flyToCruise: { es: "Desayuno en tu hotel de El Cairo. A la hora indicada, traslado al aeropuerto para tu vuelo a Lúxor o Asuán. Al llegar, embarcarás en tu crucero de lujo. Disfruta del almuerzo y la cena a bordo (Pensión completa).", en: "Breakfast at your Cairo hotel. At the designated time, transfer to the airport for your flight to Luxor or Aswan. Upon arrival, you will embark on your luxury cruise. Enjoy lunch and dinner on board (Full board).", ar: "إفطار في فندقك بالقاهرة. في الوقت المحدد، سيتم نقلك إلى المطار لرحلتك إلى الأقصر أو أسوان. عند الوصول، ستصعد على متن رحلتك النيلية الفاخرة. استمتع بالغداء والعشاء على متن السفينة (إقامة كاملة)." },
                nileSailing: { es: "Pensión completa a bordo. Hoy la navegación por el Nilo te revelará paisajes milenarios y templos majestuosos como Kom Ombo y Edfu, testigos silenciosos de la historia faraónica. Disfruta de las instalaciones del barco y de las vistas panorámicas.", en: "Full board on board. Today, sailing on the Nile will reveal ancient landscapes and majestic temples like Kom Ombo and Edfu, silent witnesses of pharaonic history. Enjoy the ship's facilities and panoramic views.", ar: "إقامة كاملة على متن السفينة. اليوم، سيكشف لك الإبحار في النيل عن مناظر طبيعية قديمة ومعابد مهيبة مثل كوم أمبو وإدفو، شهود صامتون على التاريخ الفرعوني. استمتع بمرافق السفينة والمناظر البانورامية." },
                returnToCairo: { es: "Después del desayuno en el crucero, desembarcarás y te trasladaremos al aeropuerto para tu vuelo de regreso a El Cairo. A tu llegada, traslado a tu hotel para tu última noche. (Alojamiento con desayuno).", en: "After breakfast on the cruise, you will disembark and we will transfer you to the airport for your flight back to Cairo. Upon arrival, transfer to your hotel for your final night. (Accommodation with breakfast).", ar: "بعد الإفطار على متن السفينة، ستنزل وسيتم نقلك إلى المطار لرحلتك العائدة إلى القاهرة. عند الوصول، سيتم نقلك إلى فندقك لليلة الأخيرة. (إقامة مع وجبة الإفطار)." },
                departure: { es: "Desayuno en tu hotel. A la hora acordada, nuestro representante te acompañará al Aeropuerto Internacional de El Cairo para tu vuelo de regreso, llevando contigo el alma de Egipto.", en: "Breakfast at your hotel. At the agreed time, our representative will escort you to Cairo International Airport for your return flight, taking the soul of Egypt with you.", ar: "إفطار في فندقك. في الوقت المتفق عليه، سيرافقك ممثلنا إلى مطار القاهرة الدولي لرحلة العودة، آخذاً معك روح مصر." },
            },
            optionalToursByCity: {
                cairo: { es: "el Museo de la Civilización Egipcia, el histórico Cairo Copto o un paseo en faluca por el Nilo", en: "the Museum of Egyptian Civilization, historic Coptic Cairo, or a felucca ride on the Nile", ar: "متحف الحضارة المصرية، القاهرة القبطية التاريخية، أو جولة بالفلوكة في النيل" },
                luxor: { es: "un vuelo en globo al amanecer sobre el Valle de los Reyes o el espectáculo de Luz y Sonido en el Templo de Karnak", en: "a sunrise hot air balloon ride over the Valley of the Kings or the Sound and Light show at Karnak Temple", ar: "رحلة بالمنطاد عند شروق الشمس فوق وادي الملوك أو عرض الصوت والضوء في معبد الكرنك" },
                aswan: { es: "el poblado Nubio para conocer su vibrante cultura, o los Jardines Botánicos en la Isla de Kitchener", en: "the Nubian village to experience its vibrant culture, or the Botanical Gardens on Kitchener's Island", ar: "القرية النوبية لتجربة ثقافتهم النابضة بالحياة، أو الحدائق النباتية في جزيرة كتشنر" },
            },
            serviceStrings: {
                accommodation: { es: "{nights} noches en {city} en el hotel {hotel} (o similar) {board}", en: "{nights} nights in {city} at {hotel} (or similar) {board}", ar: "{nights} ليالٍ في {city} في فندق {hotel} (أو ما شابه) {board}" },
                breakfastBoard: { es: "con desayuno incluido", en: "with breakfast included", ar: "شامل وجبة الإفطار" },
                fullBoard: { es: "con pensión completa", en: "with full board", ar: "شامل إقامة كاملة" },
                domesticFlights: { es: "Vuelos domésticos (Cairo-Lúxor/Asuán-Cairo)", en: "Domestic flights (Cairo-Luxor/Aswan-Cairo)", ar: "رحلات طيران داخلية (القاهرة-الأقصر/أسوان-القاهرة)" },
            },
            genericError: "An error occurred. Please try again.",
            apiProcessingError: "An error occurred while processing your request. Please try to simplify your query or try again later.",
            quotaError: "Our AI assistant is currently experiencing high demand. Please try again in a little while.",
            apiKeyError: "There's an issue with the connection to our AI service. Our team has been notified."
        },
        ar: {
            welcomeMessages: [
                "أهلاً بك في إيجيبتورا. تخيل شروق الشمس الذهبي فوق الأهرامات بينما يشرح لك مرشد خبير أسرارها. أنا مستشارك للسفر الفاخر، فما هي المغامرة التي حلمت بها في مصر؟",
                "تحية حارة من أرض الفراعنة. في إيجيبتورا، نحن لا نصمم رحلات فحسب، بل نصنع إرثًا. هل أنت مستعد لبدء تصميم إرثك؟",
                "أهلاً بك. فكر في همس النيل من على سطح سفينة فاخرة. هذا هو السلام الذي نقدمه. أنا مستشارك الشخصي في إيجيبتورا، كيف يمكننا البدء في رسم خريطتك؟",
            ],
            tagline: "دليلك إلى أسرار مصر",
            sendButton: "إرسال",
            suggestions: [
                "أريد رحلة لمدة 8 أيام مع رحلة نيلية",
                "ما هي البرامج المتاحة؟",
                "أخبرني عن الفئة الماسية",
                "أحتاج إلى رحلة مخصصة",
                "هل السفر إلى مصر آمن؟",
                "أرني رحلة قصيرة إلى القاهرة",
            ],
            loadingMessages: [
                "جاري استشارة البرديات القديمة...",
                "جاري رسم مسارك على خريطة الفراعنة...",
                "جاري إضافة لمسة من السحر إلى خط سير رحلتك...",
                "جاري تصميم تجربة فريدة لك...",
                "جاري وضع اللمسات الأخيرة على مغامرتك الكبرى التالية...",
            ],
            chatPlaceholder: "اكتب استفسارك عن مصر...",
            cardViewDetails: "عرض التفاصيل",
            cardRequestQuote: "طلب عرض سعر",
            cardSaveChanges: "حفظ الرحلة",
            cardShare: "مشاركة الرحلة",
            cardLoadSaved: "تحميل الرحلة المحفوظة",
            cardNights: "ليالٍ",
            cardDays: "أيام",
            cardLabelDuration: "أيام / ليالي",
            cardLabelCruiseNights: "ليالي الكروز",
            cardNightCruise: "ليلة في الكروز",
            cardNightsCruise: "ليالٍ في الكروز",
            cardStart: "البداية",
            cardGuide: "مرشد",
            modalOverview: "نظرة عامة",
            modalItinerary: "خط سير الرحلة",
            modalAccommodation: "الإقامة",
            modalPricing: "الأسعار والخيارات",
            modalIncluded: "الخدمات المتضمنة",
            modalExcluded: "الخدمات غير المتضمنة",
            modalImportantNotes: "ملاحظات هامة",
            modalSelectCategory: "1. اختر فئة",
            modalCategoryGold: "الفئة الذهبية",
            modalCategoryGoldDesc: "فنادق 5 نجوم وخدمة شخصية.",
            modalCategoryDiamond: "الفئة الماسية",
            modalCategoryDiamondDesc: "فنادق 5 نجوم ديلوكس وتجارب لكبار الشخصيات.",
            modalPricesBySeason: "2. الأسعار حسب الموسم",
            modalSummerSeason: "موسم الصيف (مايو-سبتمبر)",
            modalWinterSeason: "موسم الشتاء (أكتوبر-أبريل)",
            modalPriceDouble: "غرفة مزدوجة",
            modalPriceTriple: "غرفة ثلاثية",
            modalPriceSingle: "غرفة فردية",
            modalPerPerson: "للشخص الواحد",
            modalItineraryOptions: "هذا البرنامج له مسارات متعددة. اختر خيارًا:",
            modalQuoteButton: "طلب عرض سعر",
            modalContactButton: "اتصل بالوكيل",
            modalExchangeRate: "سعر الصرف الرسمي اليوم:",
            modalExchangeRateDisclaimer: "الأسعار بالدولار الأمريكي.",
            modalDay: "اليوم",
            modalCategory: "الفئة",
            sampleAccommodations: "أمثلة على أماكن الإقامة",
            modalInfoDaysNights: "أيام / ليالي",
            modalInfoStartIn: "يبدأ في",
            modalInfoCruiseNights: "ليالٍ في الكروز",
            modalInfoCategories: "الفئات",
            customQuoteTitle: "رحلتك المخصصة لمدة {duration} يومًا",
            customQuoteCategory: "فئة {category}",
            customQuoteOverviewText: "نظرة عامة على رحلتك المخصصة لمدة {duration} يومًا لـ {travelers} مسافر، لاستكشاف كنوز مصر.",
            customQuoteTabOverview: "نظرة عامة",
            customQuoteTabItinerary: "يوم بيوم",
            customQuoteTabPricing: "الأسعار",
            customQuoteCreated: "لقد صممت رحلة خاصة لك! إليك كل التفاصيل.",
            totalGroupPriceLabel: "السعر الإجمالي للمجموعة",
            forTravelersLabel: "لـ {travelers} مسافرين",
            pricePerPersonLabel: "السعر للشخص الواحد",
            averageLabel: "(متوسط)",
            
            // النصوص الجديدة المضافة هنا
            modalNights: 'ليالي',
            modalNoAccommodation: 'لا توجد معلومات عن الإقامة',
            modalProgramDescription: 'وصف البرنامج',
            modalCustomProgramDetails: 'تفاصيل البرنامج المخصص',
            modalTravelers: 'المسافرون',
            modalSeason: 'الموسم',
            modalDuration: 'المدة',
            modalDays: 'أيام',
            
            fallbackDayTitles: {
                arrival: { es: "Llegada a El Cairo, la Tierra de los Faraones", en: "Arrival in Cairo, Land of the Pharaohs", ar: "الوصول إلى القاهرة، أرض الفراعنة" },
                cairoTour: { es: "Explorando los Tesoros de El Cairo", en: "Exploring the Treasures of Cairo", ar: "استكشاف كنوز القاهرة" },
                flyToCruise: { es: "Vuelo a Lúxor/Asuán e Inicio del Crucero", en: "Flight to Luxor/Aswan & Cruise Embarkation", ar: "رحلة طيران إلى الأقصر/أسوان وبدء الرحلة النيلية" },
                nileSailing: { es: "Navegando las Aguas Eternas del Nilo", en: "Sailing the Eternal Waters of the Nile", ar: "الإبحار في مياه النيل الخالدة" },
                returnToCairo: { es: "Regreso a la Vibrante Capital", en: "Return to the Vibrant Capital", ar: "العودة إلى العاصمة النابضة بالحياة" },
                departure: { es: "Salida de El Cairo con Recuerdos Inolvidables", en: "Departure from Cairo with Unforgettable Memories", ar: "المغادرة من القاهرة بذكريات لا تُنسى" },
            },
            fallbackDayActivities: {
                arrival: { es: "A tu llegada al Aeropuerto Internacional de El Cairo, nuestro representante te dará una cálida bienvenida y te ayudará con los trámites de visado. Luego, un traslado privado te llevará a tu hotel para que te instales y descanses. (Alojamiento con desayuno).", en: "Upon arrival at Cairo International Airport, our representative will give you a warm welcome and assist with visa procedures. Afterwards, a private transfer will take you to your hotel to check in and rest. (Accommodation with breakfast).", ar: "عند وصولك إلى مطار القاهرة الدولي، سيستقبلك ممثلنا بحفاوة ويساعدك في إجراءات التأشيرة. بعد ذلك، ستنقلك سيارة خاصة إلى فندقك لتسجيل الدخول والراحة. (إقامة مع وجبة الإفطار)." },
                cairoFreeDay: { es: "Desayuno en tu hotel. Hoy es un día para explorar a tu propio ritmo. Te sugerimos una visita opcional a {suggestions}. ¡Permítenos ayudarte a diseñar el día perfecto!", en: "Breakfast at your hotel. Today is a day to explore at your own pace. We suggest an optional visit to {suggestions}. Let us help you design the perfect day!", ar: "إفطار في فندقك. اليوم هو يوم للاستكشاف حسب رغبتك. نقترح زيارة اختيارية إلى {suggestions}. دعنا نساعدك في تصميم اليوم المثالي!" },
                flyToCruise: { es: "Desayuno en tu hotel de El Cairo. A la hora indicada, traslado al aeropuerto para tu vuelo a Lúxor o Asuán. Al llegar, embarcarás en tu crucero de lujo. Disfruta del almuerzo y la cena a bordo (Pensión completa).", en: "Breakfast at your Cairo hotel. At the designated time, transfer to the airport for your flight to Luxor or Aswan. Upon arrival, you will embark on your luxury cruise. Enjoy lunch and dinner on board (Full board).", ar: "إفطار في فندقك بالقاهرة. في الوقت المحدد، سيتم نقلك إلى المطار لرحلتك إلى الأقصر أو أسوان. عند الوصول، ستصعد على متن رحلتك النيلية الفاخرة. استمتع بالغداء والعشاء على متن السفينة (إقامة كاملة)." },
                nileSailing: { es: "Pensión completa a bordo. Hoy la navegación por el Nilo te revelará paisajes milenarios y templos majestuosos como Kom Ombo y Edfu, testigos silenciosos de la historia faraónica. Disfruta de las instalaciones del barco y de las vistas panorámicas.", en: "Full board on board. Today, sailing on the Nile will reveal ancient landscapes and majestic temples like Kom Ombo and Edfu, silent witnesses of pharaonic history. Enjoy the ship's facilities and panoramic views.", ar: "إقامة كاملة على متن السفينة. اليوم، سيكشف لك الإبحار في النيل عن مناظر طبيعية قديمة ومعابد مهيبة مثل كوم أمبو وإدفو، شهود صامتون على التاريخ الفرعوني. استمتع بمرافق السفينة والمناظر البانورامية." },
                returnToCairo: { es: "Después del desayuno en el crucero, desembarcarás y te trasladaremos al aeropuerto para tu vuelo de regreso a El Cairo. A tu llegada, traslado a tu hotel para tu última noche. (Alojamiento con desayuno).", en: "After breakfast on the cruise, you will disembark and we will transfer you to the airport for your flight back to Cairo. Upon arrival, transfer to your hotel for your final night. (Accommodation with breakfast).", ar: "بعد الإفطار على متن السفينة، ستنزل وسيتم نقلك إلى المطار لرحلتك العائدة إلى القاهرة. عند الوصول، سيتم نقلك إلى فندقك لليلة الأخيرة. (إقامة مع وجبة الإفطار)." },
                departure: { es: "Desayuno en tu hotel. A la hora acordada, nuestro representante te acompañará al Aeropuerto Internacional de El Cairo para tu vuelo de regreso, llevando contigo el alma de Egipto.", en: "Breakfast at your hotel. At the agreed time, our representative will escort you to Cairo International Airport for your return flight, taking the soul of Egypt with you.", ar: "إفطار في فندقك. في الوقت المتفق عليه، سيرافقك ممثلنا إلى مطار القاهرة الدولي لرحلة العودة، آخذاً معك روح مصر." },
            },
            optionalToursByCity: {
                cairo: { es: "el Museo de la Civilización Egipcia, el histórico Cairo Copto o un paseo en faluca por el Nilo", en: "the Museum of Egyptian Civilization, historic Coptic Cairo, or a felucca ride on the Nile", ar: "متحف الحضارة المصرية، القاهرة القبطية التاريخية، أو جولة بالفلوكة في النيل" },
                luxor: { es: "un vuelo en globo al amanecer sobre el Valle de los Reyes o el espectáculo de Luz y Sonido en el Templo de Karnak", en: "a sunrise hot air balloon ride over the Valley of the Kings or the Sound and Light show at Karnak Temple", ar: "رحلة بالمنطاد عند شروق الشمس فوق وادي الملوك أو عرض الصوت والضوء في معبد الكرنك" },
                aswan: { es: "el poblado Nubio para conocer su vibrante cultura, o los Jardines Botánicos en la Isla de Kitchener", en: "the Nubian village to experience its vibrant culture, or the Botanical Gardens on Kitchener's Island", ar: "القرية النوبية لتجربة ثقافتهم النابضة بالحياة، أو الحدائق النباتية في جزيرة كتشنر" },
            },
            serviceStrings: {
                accommodation: { es: "{nights} noches en {city} en el hotel {hotel} (o similar) {board}", en: "{nights} nights in {city} at {hotel} (or similar) {board}", ar: "{nights} ليالٍ في {city} في فندق {hotel} (أو ما شابه) {board}" },
                breakfastBoard: { es: "con desayuno incluido", en: "with breakfast included", ar: "شامل وجبة الإفطار" },
                fullBoard: { es: "con pensión completa", en: "with full board", ar: "شامل إقامة كاملة" },
                domesticFlights: { es: "Vuelos domésticos (Cairo-Lúxor/Asuán-Cairo)", en: "Domestic flights (Cairo-Luxor/Aswan-Cairo)", ar: "رحلات طيران داخلية (القاهرة-الأقصر/أسوان-القاهرة)" },
            },
            genericError: "حدث خطأ. يرجى المحاولة مرة أخرى.",
            apiProcessingError: "حدث خطأ أثناء معالجة طلبك. يرجى محاولة تبسيط استفسارك أو المحاولة مرة أخرى لاحقًا.",
            quotaError: "مساعدنا الرقمي يواجه حاليًا طلبًا مرتفعًا. يرجى المحاولة مرة أخرى بعد قليل.",
            apiKeyError: "هناك مشكلة في الاتصال بخدمة الذكاء الاصطناعي لدينا. تم إخطار فريقنا."
        }
    }
};